source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in archiver.gemspec
gemspec
gem 'activerecord', '~> 5.2', '>= 5.2.3'